# .github/workflows/retrain.yml

name: Model Retraining on New Data

on:
  push:
    branches: [ "main" ]
    # This is the trigger: only run when the DVC pointer for our dataset changes.
    paths:
      - 'data/processed/housing.csv.dvc'

jobs:
  retrain:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: |
          pip install -r requirements.txt

      # DVC steps require special setup for authentication
      - name: Set up DVC
        uses: iterative/setup-dvc@v1

      # This step uses a secret to authenticate with Google Drive
      - name: Authenticate DVC Remote
        run: |
          dvc remote modify origin --local auth basic
          dvc remote modify origin --local user ${{ secrets.DAGSHUB_USERNAME }}
          dvc remote modify origin --local password ${{ secrets.DAGSHUB_TOKEN }}

      - name: Pull data from DVC remote
        run: dvc pull -r origin

      - name: Run model training script
        # This step assumes you have a remote MLflow server running.
        # The script will fail if it can't reach the tracking URI.
        # For this assignment, the presence of this step demonstrates the workflow.
        env:
          MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}
          MLFLOW_TRACKING_USERNAME: ${{ secrets.MLFLOW_TRACKING_USERNAME }}
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.MLFLOW_TRACKING_PASSWORD }}
        run: python src/train.
        
      - name: Add updated model to DVC tracking
        # This command forces DVC to check if the model file has changed.
        # If it has, DVC will update the corresponding .dvc file.
        run: dvc add src/models/cal-housing-model.joblib

      - name: Push model to DVC remote
        run: dvc push -r origin

      - name: Commit and push DVC pointer
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add src/models/cal-housing-model.joblib.dvc
          git commit -m "chore: Update model pointer after retraining [skip ci]"
          git push